---
title:   "Interactive plot with plotly"
site:    workflowr::wflow_site
author:  "Author: learnusezone@gmail.com"
date:    "`r paste(\"Last update:\", format(lubridate::with_tz(as.POSIXct(Sys.time()) + 7200, tzone = \"GMT\"), \"%Y-%m-%d %H:%M GMT+2\"))`"
# from-to: 2020-12-19-
purpose: interactive scatter plot with qualitative colorscales
output:
  workflowr::wflow_html:
    toc: false
    highlight: pygments
    theme: paper
    code_folding: hide
editor_options:
  chunk_output_type: console
# note:  -
---

```{r, include = F}
knitr::opts_chunk$set(
  comment = "#>",
  eval = T
)
```


# Interactive scatter plot with qualitative colorscales
Interactive scatter plot where three species of Iris
(Iris setosa, Iris virginica and Iris versicolor) are distinguished by color.


# Load prepared data
```{r plotly_src, class.source = 'fold-show'}
knitr::read_chunk("code/examples/iris/interactive-visuals/plotly.R")
```


# Interactive scatter plot with filters
```{r plotly_Rmd_input, eval = T, warning = F, message = F}
```

